apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      text:
        type: string
        default: world
        required: true
        description: Text input to say hello
jobs:
  hello-world-job:
    steps:
      - name: Say hello
        uses: ./hello-world
        with:
          name: "John"

  hello-world-to-multiple-users-job:
    steps:
      - name: Say hello to multiple users
        uses: ./say-hello-to-multiple-users
        with:
          names: "John,Jane,Alex"

  dispatch-workflows-job:
    steps:
      - name: Dispatch Workflows
        uses: ./dispatch-workflows
        with:
          orgComponentData: |
            [
              { "org": "org1-url", "component": "component-id1" },
              { "org": "org2-url", "component": "component-id2" }
            ]
