apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      text:
        type: string
        default: world
        required: true
        description: Text input to say hello
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        params:
          text: "${{ inputs.text }}"
        run: |
          echo "hello $text"